- type: playTimeTracker
  id: JobBlueShield

- type: playTimeTracker
  id: JobCentComOfficial

- type: playTimeTracker
  id: JobCentComOperator

- type: playTimeTracker
  id: JobCentComConsultant

- type: playTimeTracker
  id: JobBrigmedic

- type: playTimeTracker
  id: JobMagistrat

- type: playTimeTracker
  id: JobSeniorEngineer

- type: playTimeTracker
  id: JobSeniorOfficer

- type: playTimeTracker
  id: JobSeniorPhysician

- type: playTimeTracker
  id: JobSeniorResearcher

- type: playTimeTracker
  id: JobRoboticist


